# Syntax: gitignore rules

# Ignore files and directories for all sections from gitignore file
# Default: True
gitignore-import-and-ignore: True

# Ignore files and directories for tree and content sections
ignore-tree-and-content:
  - ".git/"
  - "node_modules/"
  - "__pycache__/"
  - "*.lock"
  - "*.yaml"
  - "*.md"
  - "frontend/public/"
  - "*.png"
  - "*.ico"
  - "*.json"
  - "README.md"
  - "frontend/src/logo.svg"
  - "frontend/src/setupTests.js"
  - "frontend/src/App.test.js"
