# Syntax: gitignore rules

# Ignore files and directories for all sections from gitignore file
# Default: True
gitignore-import-and-ignore: True

# Ignore files and directories for tree and "Contents of ..." sections
ignore-tree-and-content:
  - "node_modules/"
  - "vendor/"
  - ".git/"
  - "__pycache__/"
